[[rules]]
name     = "'if' with 'begin'"
pattern  = '(?m)(^|[\t ])if\s'
required = '(?m)(^|[\t ])if\s*\([^)]*\)\s*begin'
ignore   = '(/\*/?([^/]|[^*]/)*\*/)|(//.*\n)'
hint     = "'if' statement must have 'begin'"
includes = ["**/*.v", "**/*.sv"]
excludes = []

[[rules]]
name     = "'else' with 'begin'"
pattern  = '(?m)(^|[\t ])else\s'
required = '(?m)(^|[\t ])else\s+(if|begin)'
ignore   = '(/\*/?([^/]|[^*]/)*\*/)|(//.*\n)'
hint     = "'else' statement must have 'begin'"
includes = ["**/*.v", "**/*.sv"]
excludes = []

[[rules]]
name      = "verilog 'always' forbidden"
pattern   = '(?m)(^|[\t ])always\s'
forbidden = '(?m)(^|[\t ])always\s'
ignore    = '(/\*/?([^/]|[^*]/)*\*/)|(//.*\n)'
hint      = "'always' must be replaced to 'always_comb'/'always_ff'"
includes  = ["**/*.v", "**/*.sv"]
excludes  = []

[[rules]]
name      = "'if' with brace"
pattern   = '(?m)(^|[\t ])if\s'
forbidden = '(?m)(^|[\t ])if\s[^;{]*$'
ignore    = '(/\*/?([^/]|[^*]/)*\*/)|(//.*\n)'
hint      = "multiline 'if' must have brace"
includes  = ["**/*.c", "**/*.cpp"]
excludes  = []
