[package]
name = "flexlint"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
repository = "https://github.com/dalance/flexlint"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "A linter with rules specified by Regular Expression"
categories = ["command-line-utilities", "development-tools"]

[dependencies]
failure      = "*"
glob         = "*"
regex        = "*"
serde        = "*"
serde_derive = "*"
structopt    = "*"
term         = "*"
toml         = "*"

[package.metadata.release]
dev-version-ext            = "pre"
pre-release-commit-message = "Prepare to v{{version}}"
pro-release-commit-message = "Start next development iteration v{{version}}"
tag-message                = "Bump version to {{version}}"
tag-prefix                 = "v"
